# This is a basic workflow to help you get started with Actions

name: CI/CD DevTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DevTest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_JSCPD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload to Dev Server
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # ftp server
          server: ${{ secrets.FTP_HOSTNAME }}
          # ftp username
          username: ${{ secrets.FTP_USERNAME }}
          # ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # Folder to upload from, must end with trailing slash /
          local-dir: ./dayzOffline.chernarusplus/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: dayzxb_missions/dayzOffline.chernarusplus/
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: github-ftp-deploy-sync-state.json.log
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: false
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          #dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          #exclude: # optional
          # How verbose should the information be - minimal, standard, or verbose
          #log-level: # optional
          # strict or loose
          #security: # optional

      - name: Restart GameServer
        run: >-
          curl 
          -X POST "https://api.nitrado.net/services/${{ secrets.NITRADO_GAMESERVER_ID }}/gameservers/restart?message=Github%20File%20Upload%20Requires%20Restart" 
          -H "Authorization: ${{ secrets.NITRADO_TOKEN }}"
